// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOmApFMqxJAOF3u7vrkeSnDK8xj2G_glI',
    appId: '1:878335239927:web:b15a36863df1c4368a95f2',
    messagingSenderId: '878335239927',
    projectId: 'imagegen-trail',
    authDomain: 'imagegen-trail.firebaseapp.com',
    storageBucket: 'imagegen-trail.firebasestorage.app',
    measurementId: 'G-YL6CFFCZ2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiEKEi6jbAXiDndhyq9GqrZJ0SvgbC7IQ',
    appId: '1:878335239927:android:263634b1a789a19e8a95f2',
    messagingSenderId: '878335239927',
    projectId: 'imagegen-trail',
    storageBucket: 'imagegen-trail.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgNsj58I5lTHshyIPDxIGbwhqN_ZJjM7A',
    appId: '1:878335239927:ios:dc1cda6f874a5a038a95f2',
    messagingSenderId: '878335239927',
    projectId: 'imagegen-trail',
    storageBucket: 'imagegen-trail.firebasestorage.app',
    iosBundleId: 'com.example.trailAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgNsj58I5lTHshyIPDxIGbwhqN_ZJjM7A',
    appId: '1:878335239927:ios:dc1cda6f874a5a038a95f2',
    messagingSenderId: '878335239927',
    projectId: 'imagegen-trail',
    storageBucket: 'imagegen-trail.firebasestorage.app',
    iosBundleId: 'com.example.trailAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDncGJeA3FtRy2aL94plnmXnXWnZIHspGY',
    appId: '1:878335239927:web:584efea4a332aca18a95f2',
    messagingSenderId: '878335239927',
    projectId: 'imagegen-trail',
    authDomain: 'imagegen-trail.firebaseapp.com',
    storageBucket: 'imagegen-trail.firebasestorage.app',
    measurementId: 'G-HN75QB64GM',
  );

}